/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.Naves;

import Fabrica.Fabrica;
import Interface.InterfaceEspacial;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JOptionPane;

/**
 *
 * @author laptopwin
 */
public class Crear_Nave_Lanzadera extends javax.swing.JFrame {

    private final InterfaceEspacial IE;
    
    public Crear_Nave_Lanzadera() {
        initComponents();
        this.IE = Fabrica.getInstance().getIControladorEspacial();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setTitle("Creando Nave Lanzadera");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabeldestinoViajera = new javax.swing.JLabel();
        txtnombre_Lanzadera = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Descripcion_Lanzadera = new javax.swing.JTextArea();
        txtCargaLanzadera = new javax.swing.JTextField();
        JLabelnombreViajera = new javax.swing.JLabel();
        as = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        s = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtPotenciaviajera = new javax.swing.JSpinner();
        txtcombustible = new javax.swing.JTextField();
        JLabelnombreViajera1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabeldestinoViajera.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabeldestinoViajera.setText("Carga");

        txtnombre_Lanzadera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombre_LanzaderaActionPerformed(evt);
            }
        });

        Descripcion_Lanzadera.setColumns(20);
        Descripcion_Lanzadera.setRows(5);
        Descripcion_Lanzadera.setPreferredSize(new java.awt.Dimension(110, 94));
        jScrollPane2.setViewportView(Descripcion_Lanzadera);

        txtCargaLanzadera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargaLanzaderaActionPerformed(evt);
            }
        });

        JLabelnombreViajera.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLabelnombreViajera.setText("Nombre:");

        as.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        as.setText("Potencia:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Descripcion:");

        s.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        s.setText("Combustible:");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtcombustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcombustibleActionPerformed(evt);
            }
        });

        JLabelnombreViajera1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLabelnombreViajera1.setText("Creando Nave");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLabelnombreViajera)
                                    .addComponent(jLabeldestinoViajera)
                                    .addComponent(as)
                                    .addComponent(s))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLabelnombreViajera1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCargaLanzadera, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                        .addComponent(txtnombre_Lanzadera, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                        .addComponent(txtPotenciaviajera)
                                        .addComponent(txtcombustible)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLabelnombreViajera1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelnombreViajera)
                    .addComponent(txtnombre_Lanzadera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCargaLanzadera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeldestinoViajera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(as)
                    .addComponent(txtPotenciaviajera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s)
                    .addComponent(txtcombustible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombre_LanzaderaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombre_LanzaderaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombre_LanzaderaActionPerformed

    private void txtCargaLanzaderaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargaLanzaderaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargaLanzaderaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre = txtnombre_Lanzadera.getText();
        String carga = txtCargaLanzadera.getText();
        String desc = Descripcion_Lanzadera.getText();
        int potencia = (int) txtPotenciaviajera.getValue();
        String combustible =  txtcombustible.getText();
        
       
        boolean continuar = true;
        if(nombre.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "El nombre es obligatorio.");
            continuar = false;
        }
         if(carga.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "El nombre de la carga es obligatorio.");
            continuar = false;
        }
        
        if(combustible.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "El combustible es obligatorio.");
            continuar = false;
        }
        
        if(desc.isEmpty() && continuar)
        {
            JOptionPane.showMessageDialog(this, "La descripcion es obligatorio.");
            continuar = false;
        }
            
        if(potencia <=0 && continuar)
        {
            JOptionPane.showMessageDialog(this, "La potencia tiene que ser mayor a 0.");
            continuar = false;
        }
        
        if(continuar) //Es que esta todo OK
        {
            String resultado = IE.CreandoNaveLanzadera(nombre, desc, potencia, carga, combustible);//Tengo que hacer la funcion en el controlador
            if(resultado == "V")//Todo OK
            {
                JOptionPane.showMessageDialog(this, "Nave creada con exito.");
                dispose();
            }else{
                if(resultado == "I") //Ya existe ese nombre
                {
                    JOptionPane.showMessageDialog(this, "El nombre ya existe.");
                }else{
                    JOptionPane.showMessageDialog(this, "Erro a la hora de crear la Nave  .");
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtcombustibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcombustibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcombustibleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crear_Nave_Lanzadera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crear_Nave_Lanzadera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crear_Nave_Lanzadera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crear_Nave_Lanzadera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crear_Nave_Lanzadera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Descripcion_Lanzadera;
    private javax.swing.JLabel JLabelnombreViajera;
    private javax.swing.JLabel JLabelnombreViajera1;
    private javax.swing.JLabel as;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabeldestinoViajera;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel s;
    private javax.swing.JTextField txtCargaLanzadera;
    private javax.swing.JSpinner txtPotenciaviajera;
    private javax.swing.JTextField txtcombustible;
    private javax.swing.JTextField txtnombre_Lanzadera;
    // End of variables declaration//GEN-END:variables
}
