/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.Naves;

import Fabrica.Fabrica;
import Interface.InterfaceEspacial;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian González
 */
public class Crear_Nave_Robotica extends javax.swing.JFrame {

    
    
    private InterfaceEspacial IE ;
    public Crear_Nave_Robotica() {
        initComponents();
        this.IE = Fabrica.getInstance().getIControladorEspacial();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDestinoro = new javax.swing.JTextField();
        JLabelnombreViajera = new javax.swing.JLabel();
        as = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabeldestinoViajera = new javax.swing.JLabel();
        txtnombre_ro = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Descripcion_robotica = new javax.swing.JTextArea();
        as1 = new javax.swing.JLabel();
        Aceptar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        txtPotenciarobo = new javax.swing.JSpinner();
        JLabelnombreViajera1 = new javax.swing.JLabel();
        txtPlaneta = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtDestinoro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDestinoroActionPerformed(evt);
            }
        });

        JLabelnombreViajera.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLabelnombreViajera.setText("Nombre:");

        as.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        as.setText("Potencia:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Descripcion:");

        jLabeldestinoViajera.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabeldestinoViajera.setText("Tipo Combustible:");

        txtnombre_ro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombre_roActionPerformed(evt);
            }
        });

        Descripcion_robotica.setColumns(20);
        Descripcion_robotica.setRows(5);
        Descripcion_robotica.setPreferredSize(new java.awt.Dimension(110, 94));
        jScrollPane2.setViewportView(Descripcion_robotica);

        as1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        as1.setText("Planeta a Estudiar : ");

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        JLabelnombreViajera1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLabelnombreViajera1.setText("Creando Nave");

        txtPlaneta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saturno y sus lunas", "Jupiter", "Martes", "Mercurio", "Plutón", "Urano y Neptuno", "Sol", "Venus" }));
        txtPlaneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlanetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Aceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Cancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(as1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPlaneta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabeldestinoViajera)
                            .addComponent(as)
                            .addComponent(JLabelnombreViajera))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnombre_ro)
                            .addComponent(txtDestinoro)
                            .addComponent(txtPotenciarobo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(JLabelnombreViajera1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JLabelnombreViajera1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelnombreViajera)
                    .addComponent(txtnombre_ro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDestinoro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeldestinoViajera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPotenciarobo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(as))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(as1)
                    .addComponent(txtPlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aceptar)
                    .addComponent(Cancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDestinoroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinoroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinoroActionPerformed

    private void txtnombre_roActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombre_roActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombre_roActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        String nombre = txtnombre_ro.getText();
        String desc = Descripcion_robotica.getText();
        String destino = txtDestinoro.getText();
        String Planeta = (String) txtPlaneta.getSelectedItem();
        int potencia = (int)txtPotenciarobo.getValue();
       
        boolean continuar = true;
        if(nombre.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "El nombre es obligatorio.");
            continuar = false;
        }
        
         if(potencia <=0 && continuar)
        {
            JOptionPane.showMessageDialog(this, "La Potencia debe ser mayor a 0 .");
            continuar = false;
        }
        
        if(destino.isEmpty()&& continuar)
        {
            JOptionPane.showMessageDialog(this, "El Destino es obligatorio.");
            continuar = false;
        }
       
        if(desc.isEmpty() && continuar)
        {
            JOptionPane.showMessageDialog(this, "La descripcion es obligatorio.");
            continuar = false;
        }
        
         if(Planeta.isEmpty() && continuar)
        {
            JOptionPane.showMessageDialog(this, "El planeta al que se quiere estudiar es obligatorio.");
            continuar = false;
        }
            
       
        if(continuar) //Es que esta todo OK
        {
            String resultado = IE.CreandoNaveRobotica(nombre,desc,potencia,Planeta,destino);//Tengo que hacer la funcion en el controlador
            if(resultado == "V")//Todo OK
            {
                JOptionPane.showMessageDialog(this, "Nave creada con exito.");
                dispose();
            }else{
                if(resultado == "I") //Ya existe ese nombre
                {
                    JOptionPane.showMessageDialog(this, "El nombre ya existe.");
                }else{
                    JOptionPane.showMessageDialog(this, "Erro a la hora de crear la nave  .");
                }
            }
        }
        
    }//GEN-LAST:event_AceptarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void txtPlanetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlanetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlanetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crear_Nave_Robotica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crear_Nave_Robotica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crear_Nave_Robotica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crear_Nave_Robotica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crear_Nave_Robotica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextArea Descripcion_robotica;
    private javax.swing.JLabel JLabelnombreViajera;
    private javax.swing.JLabel JLabelnombreViajera1;
    private javax.swing.JLabel as;
    private javax.swing.JLabel as1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabeldestinoViajera;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtDestinoro;
    private javax.swing.JComboBox<String> txtPlaneta;
    private javax.swing.JSpinner txtPotenciarobo;
    private javax.swing.JTextField txtnombre_ro;
    // End of variables declaration//GEN-END:variables
}
